[platformio]
default_envs = m5stack-cardputer

[env:m5stack-cardputer]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -DESP32S3
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO
lib_deps =
    https://github.com/m5stack/M5Gfx
    https://github.com/m5stack/M5Unified
    https://github.com/m5stack/M5Cardputer